apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  # Specify cluster name. It is useful in multi-cluster env.
  clusterName: TO_BE_FIXED

charts:
- name: ingress-nginx
  override:

- name: k8s-cluster-autoscaler
  override:
    image:
      tag: v1.25.1
    awsRegion: ap-northeast-2
    autoDiscovery:
      clusterName: $(clusterName)

- name: cluster-autoscaler
  override:
    discoveryNamespace: $(clusterName)
    discoveryClusterName: $(clusterName)

- name: cluster-autoscaler-rbac
  override:
    deployMgmtRbacOnly.targetNamespace: $(clusterName)

- name: argo-rollouts
  override:
    controller:
      nodeSelector:
        taco-lma: enabled
      replicas: 2
      image:
        registry: harbor-cicd.taco-cat.xyz
        repository: tks/argo-rollouts
        tag: v1.4.1
